# Generated by Django 2.1.3 on 2019-01-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20181228_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='event',
            field=models.ForeignKey(default='暂无发布会', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='sign.Event'),
        ),
    ]
