# Generated by Django 2.1.3 on 2019-01-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0006_auto_20190109_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(3), to='sign.Event'),
        ),
    ]
